// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddCandidateTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addCandidate() {
    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("Admin");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.cssSelector(".oxd-button")).click();
    driver.findElement(By.cssSelector(".oxd-main-menu-item-wrapper:nth-child(5) .oxd-text")).click();
    driver.findElement(By.cssSelector(".oxd-button--secondary:nth-child(1)")).click();
    driver.findElement(By.name("firstName")).click();
    driver.findElement(By.name("firstName")).sendKeys("Maria");
    driver.findElement(By.name("middleName")).sendKeys("Fernanda");
    driver.findElement(By.name("lastName")).sendKeys("Avendaño");
    driver.findElement(By.cssSelector(".oxd-select-text-input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".oxd-form-row:nth-child(3) .oxd-grid-item:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".oxd-button--success")).click();
    driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
    driver.findElement(By.cssSelector(".oxd-button--success")).click();
    driver.findElement(By.cssSelector(".oxd-input--focus")).click();
    driver.findElement(By.cssSelector(".oxd-input--focus")).sendKeys("Interview");
    driver.findElement(By.cssSelector(".oxd-autocomplete-text-input > input")).click();
    driver.findElement(By.cssSelector(".oxd-autocomplete-text-input > input")).sendKeys("Charles  Carter");
    {
      WebElement element = driver.findElement(By.cssSelector(".oxd-form-row:nth-child(2) .oxd-grid-item:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".oxd-button--success")).click();
    driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".oxd-button--secondary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".oxd-button:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
    driver.findElement(By.cssSelector(".oxd-button--success")).click();
    driver.findElement(By.cssSelector(".oxd-button--secondary")).click();
    driver.findElement(By.linkText("Candidates")).click();
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(1) .oxd-table-card-cell-checkbox .oxd-icon")).click();
    driver.findElement(By.cssSelector(".oxd-table-card:nth-child(1) .oxd-icon-button:nth-child(1) > .oxd-icon")).click();
  }
}
